@startuml LodeRunner.API App and Change feed Init

participant "App" as L8rAPIStart
participant "WebHost" as WebHost
collections "Controllers" as Endpoints #Orange
participant "Loggers" as Loggers
database    "CosmosDB" as CosmosDB

[o-> L8rAPIStart: Start LodeRunner.API

activate L8rAPIStart

L8rAPIStart -> L8rAPIStart: Validate Arguments
L8rAPIStart -> L8rAPIStart: Creates Start-up Config

L8rAPIStart -> L8rAPIStart: Ensure secrets
L8rAPIStart -> Loggers: Initialize Loggers
activate Loggers
Loggers --> L8rAPIStart
deactivate Loggers
L8rAPIStart -> L8rAPIStart: Register Temination Events

L8rAPIStart -> WebHost: Build and Configures Host
activate WebHost #LightGreen
note right
    Registers Controllers, Routes, Config, CosmosDBSettings, Uses Startup class
end note
WebHost -> Endpoints: Ready controllers
activate Endpoints #Orange
Endpoints --> WebHost
deactivate Endpoints
WebHost --> L8rAPIStart

CosmosDB -> Endpoints: Document Queries
activate CosmosDB
Endpoints --> CosmosDB
deactivate CosmosDB

deactivate Endpoints

deactivate WebHost


@enduml