apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.lrApiName}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.lrApiName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.lrApiName}}
  template:
    metadata:
      labels:
        app: {{gitops.lrApiName}}
        aadpodidbinding: {{gitops.lrMiName}}
    spec:
      containers:
        - name: app
          image: {{gitops.lrApiImage}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: lr-secrets
      nodeSelector:
        agentpool: npuser01

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.lrApiName}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.lrApiName}}
