
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{gitops.lrmi.name}}
  namespace: {{gitops.namespace}}
spec:
  type: 0
  resourceID: /subscriptions/{{gitops.tenantid}}/resourcegroups/{{gitops.resourceGroup}}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{gitops.lrmi.name}}
  clientID: {{gitops.lrmi.clientId}}

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{gitops.lrmi.name}}-binding
  namespace: {{gitops.namespace}}
spec:
  azureIdentity: {{gitops.lrmi.name}}
  selector: {{gitops.lrmi.name}}

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: lr-secrets
  namespace: {{gitops.namespace}} 
spec:
  provider: azure
  secretObjects:
  - secretName: {{gitops.secretKeys.cosmosDatabase.keyvault}}
    type: Opaque
    data:
    - objectName: {{gitops.secretKeys.cosmosDatabase.volume}}
      key: key
  - secretName: {{gitops.secretKeys.cosmosCollection.keyvault}}
    type: Opaque
    data:
    - objectName: {{gitops.secretKeys.cosmosCollection.volume}}
      key: key
  - secretName: {{gitops.secretKeys.cosmosKey.keyvault}}
    type: Opaque
    data:
    - objectName: {{gitops.secretKeys.cosmosKey.volume}}
      key: key
  - secretName: {{gitops.secretKeys.cosmosUrl.keyvault}}
    type: Opaque
    data:
    - objectName: {{gitops.secretKeys.cosmosUrl.volume}}
      key: key
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-aks-3i2qzkkxofr7c"
    objects: |
      array:
        - |
          objectName: {{gitops.secretKeys.cosmosDatabase.volume}}
          objectType: secret
        - |
          objectName: {{gitops.secretKeys.cosmosCollection.volume}}
          objectType: secret
        - |
          objectName: {{gitops.secretKeys.cosmosKey.volume}}
          objectType: secret
        - |
          objectName: {{gitops.secretKeys.cosmosUrl.volume}}
          objectType: secret
    tenantId: {{gitops.tenantid}}