apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner-ui
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-ui
  template:
    metadata:
      labels:
        app: loderunner-ui
    spec:
      containers:
        - name: app
          image: k3d-registry.localhost:5000/loderunner-ui:local
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: "LRAPI_DNS"
            value: ""
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-ui
  namespace: loderunner
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http 
    nodePort: 32080
    protocol: TCP
    name: http
  selector:
    app: loderunner-ui
