apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner-api
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-api
  template:
    metadata:
      labels:
        app: loderunner-api
    spec:
      containers:
        - name: app
          image: k3d-registry.localhost:5000/loderunner-api:local
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: SSL_CERT_DIR
            value: /certs/
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
              volumeMounts:
            - name: cosmos-emul-secrets
              mountPath: /certs/
              readOnly: true
      volumes:
        - name: cosmos-emul-secrets
          secret:
            secretName: cosmos-emul-secrets
            optional: false # default setting; secret must exist
            items:
            - key: nginx_cosmos_cert
              path: nginx_cosmos.pem
            - key: cosmos_emul_cert
              path: emulatorcert.pem
        - name: secrets
          secret:
            secretName: lr-secrets
            defaultMode: 444

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-api
  namespace: loderunner
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: http
      nodePort: 32088
      protocol: TCP
      name: http
  selector:
    app: loderunner-api
