apiVersion: v1
kind: Pod

metadata:
  name: loderunner-api
  labels:
    app: loderunner-api

spec:
  containers:
  - name: app
    image: k3d-registry.localhost:5000/loderunner-api:local
    imagePullPolicy: Always
    env:
    - name: "ASPNETCORE_ENVIRONMENT"
      value: "Development"
    readinessProbe:
      initialDelaySeconds: 5
      httpGet:
        path: /version
        port: 8080
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 300
      httpGet:
        path: /healthz
        port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-api
  labels:
    app: loderunner-api
spec:
  type: NodePort
  selector:
    app: loderunner-api
  ports:
  - port: 8080
    nodePort: 32088
