apiVersion: apps/v1
kind: Deployment

metadata:
  name: loderunner-baseline-cosmos
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-baseline-cosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-baseline-cosmos
  template:
    metadata:
      labels:
        app: loderunner-baseline-cosmos
    spec:
      containers:
      - name: app
        image: ghcr.io/retaildevcrews/ngsa-lr:beta
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        args:
        - -s
        - http://ngsa-cosmos:8080
        - -f
        - baseline.json
        - --prometheus
        - --zone
        - dev
        - --region
        - dev
    