apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner-ui
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-ui
  template:
    metadata:
      labels:
        app: loderunner-ui
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/loderunner-ui:beta
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-ui
  namespace: loderunner
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loderunner-ui
