apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: fluentbit
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
  namespace: fluentbit
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
  namespace: fluentbit
roleRef:
  kind: ClusterRole
  name: fluentbit
  apiGroup: ""
subjects:
- kind: ServiceAccount
  namespace: fluentbit
  name: fluentbit
  apiGroup: ""
