apiVersion: v1
kind: Pod

metadata:
  name: loderunner-ui
  labels:
    app: loderunner-ui

spec:
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/loderunner-ui:beta
    imagePullPolicy: Always
    readinessProbe:
      initialDelaySeconds: 5
      httpGet:
        path: /
        port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-ui
  labels:
    app: loderunner-ui
spec:
  type: NodePort
  selector:
    app: loderunner-ui
  ports:
    - port: 80
      nodePort: 32080
