apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-memory
  namespace: ngsa
  labels:
    app: ngsa-memory
    app.kubernetes.io/name: ngsa-memory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-memory
  template:
    metadata:
      labels:
        app: ngsa-memory
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-app:beta
          imagePullPolicy: Always
          args:
          - --in-memory
          - --prometheus
          - --log-level
          - Warning
          - --request-log-level
          - Information
          - --zone
          - dev
          - --region
          - dev
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: ngsa-memory
