name: Check Line Endings (find CRLF)

on: 
  pull_request:
    branches: [ main ]

jobs:
  check_pull_request_job:
    runs-on: ubuntu-latest
    name: Check files for CRLF line endings
    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1

    - name: Validate files with custom script
      run: |
        chmod +x "./.github/crlf-check.sh"
        ./.github/crlf-check.sh
    
    - name: Validate files with MS Graph
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
      id: validate
      uses: microsoftgraph/eol-blocker@v1.0.8
