name: markdownlint

on:
  pull_request:
      types: [opened, synchronize]

  push:
    branches:
      - main

jobs:
  markdown-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run mdl
      uses: actionshub/markdownlint@main
