name: Build LodeRunner

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: "0 6 * * *"

  push:
    branches:
      - main

    paths:
    - 'src/LodeRunner/Dockerfile'
    - 'src/LodeRunner/*.csproj'
    - 'src/LodeRunner/src/**.cs'
    - '.github/workflows/ngsa.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/retaildevcrews/ngsa-lr

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker Build
      run: |
        docker build ./src -t image -f ./src/LodeRunner/Dockerfile

    - name: Docker Tag and Push
      run: |

        VERSION=$(docker run --rm image --version)

        # tag the repo with :beta
        #docker tag image $DOCKER_REPO:beta

        # Push to the repo
        #docker push -a $DOCKER_REPO
