name: Test LodeRunner

on:
  pull_request:
    types: [opened, synchronize]

    paths:
      - 'src/LodeRunner/Dockerfile'
      - 'src/LodeRunner/*.csproj'
      - 'src/LodeRunner/src/**.cs'
      - '.github/workflows/ngsa-pr.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Docker Build LodeRunner
      run: |
        docker build ./src -t image -f ./src/LodeRunner/Dockerfile

    - name: Set Secrets
      run: |
        mkdir -p /tmp/secrets
        echo -n ${{ secrets.NGSA_DEV_COSMOS_RW_KEY }} >| /tmp/secrets/CosmosKey
        echo -n ${{ secrets.NGSA_DEV_COSMOS_URL }} >| /tmp/secrets/CosmosUrl
        echo -n 'LodeRunner' >| /tmp/secrets/CosmosCollection
        echo -n 'LodeRunnerTestDB' >| /tmp/secrets/CosmosDatabase

    - name: Docker Run LodeRunner
      run: |
        docker run -d --rm -p 80:8080 --name ngsa ghcr.io/retaildevcrews/ngsa-app:beta --in-memory

        echo "Waiting for ngsa-app to start ..."

        wait_time=10
        sleep $wait_time

        # wait up to 30 seconds for ngsa-app to start
        while true
        do
          if curl localhost:80/version ; then
            echo -e "\n ngsa-app is running"
            break
          fi
          if [ $wait_time -gt 30 ] ; then
            echo -e "\n timeout waiting for ngsa-app to start"
            exit 1
          fi

          sleep 1
          ((wait_time=wait_time+1))
        done

        echo "Running LoadRunner benchmark"

        docker run -d --rm --net=host -v /tmp/secrets:/app/secrets image --delay-start -1 --secrets-volume /app/secrets -s http://localhost:80 -f benchmark.json

      # TODO: run load test

    - name: Delete Secrets
      run: |
        rm -rf /tmp/secrets
