name: Test Variable

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: "Set flag from PR"
      env:
        TEST_RESULT: false
      run: |
        if ${TEST_RESULT} == true; then
          echo "flag=true" >> $GITHUB_ENV
          echo "flag set to true"
        else
          echo "flag=false" >> $GITHUB_ENV
          echo "flag set to false"
        fi

    - name: "Use flag if true"
      if: env.flag
      run: echo "Flag is available and true"

