name: Test Variable

on:
  pull_request:
    types: [opened, synchronize]
    
env:
  TEST_RESULT: 'success'

jobs:
  job1:
    name: Change env variable

    runs-on: ubuntu-latest
    steps:
      - name: Print value of env variable
        run: echo "TEST_RESULT = $TEST_RESULT"

      - name: Change env variable
        run: echo "true" >> $TEST_RESULT

      - name: Print new value of env variable
        run: echo "TEST_RESULT = $TEST_RESULT"

