apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.lrCommandName}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.lrCommandName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.lrCommandName}}
  template:
    metadata:
      labels:
        app: {{gitops.lrCommandName}}
        deploy: {{gitops.deploy}}
        version: beta-{{gitops.version}}
    spec:
      containers:
        - name: app
          image: {{gitops.lrImage}}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /version
              port: http
          readinessProbe:
            httpGet:
              path: /version
              port: http
          args:
          - -l
          - "1000"
          - -r
          - -s
          - http://ngsa-memory.ngsa:8080
          - http://ngsa-cosmos.ngsa:8080
          - http://ngsa-java.ngsa:8080
          - -f
          - benchmark.json
          - -p
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.lrCommandName}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.lrCommandName}}
