apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.lrApiName}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.lrApiName}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{gitops.lrApiName}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{gitops.lrApiName}}
        aadpodidbinding: {{gitops.lrMiName}}
        deploy: {{gitops.deploy}}
        version: beta-{{gitops.version}}
    spec:
      containers:
        - name: app
          image: {{gitops.lrApiImage}}
          imagePullPolicy: Always
          args:
          - --url-prefix
          - /api
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
            - mountPath: /tmp
              name: tmp
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: lr-secrets
        - name: tmp
          emptyDir: {}
      nodeSelector:
        kubernetes.azure.com/mode: user

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.lrApiName}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.lrApiName}}
